name: Build and deploy PHP app to Azure Web App - TeamManagerPro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, sqlite3
      
      # Agregar setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Ajustar directorio de trabajo si es necesario
      - name: Navigate to app directory
        run: |
          cd TeamManagerPro  # Elimina esta línea si tu app está en la raíz

      - name: Install Composer dependencies
        run: |
          cd TeamManagerPro  # Elimina esta línea si tu app está en la raíz
          composer install --prefer-dist --no-dev --optimize-autoloader

      # Compilar assets frontend
      - name: Install and build frontend assets
        run: |
          cd TeamManagerPro  # Elimina esta línea si tu app está en la raíz
          npm ci
          npm run build

      # Optimizar configuración Laravel
      - name: Optimize Laravel
        run: |
          cd TeamManagerPro  # Elimina esta línea si tu app está en la raíz
          cp .env.example .env
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      # Empaquetar solo la carpeta de la app
      - name: Zip artifact for deployment
        run: |
          cd TeamManagerPro  # Elimina esta línea si tu app está en la raíz
          zip -r ../release.zip ./* 

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C89C5973F2784F1F958E687F6B6F7B35 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E202E676DEE448729284AC5AB20688AB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8BE776FD19154B1EAE8E2B29F0FFCC8A }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TeamManagerPro'
          slot-name: 'Production'
          package: .