name: Build and deploy PHP app to Azure Web App - TeamManagerPro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, fileinfo, sqlite3

      - name: Cache Composer packages
        uses: actions/cache@v3
        with:
          path: TeamManagerPro/vendor
          key: ${{ runner.os }}-php-${{ hashFiles('TeamManagerPro/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'TeamManagerPro/package-lock.json'

      - name: Install Composer dependencies
        run: |
          cd TeamManagerPro
          composer install --prefer-dist --no-dev --optimize-autoloader

      - name: Install and build frontend assets
        run: |
          cd TeamManagerPro
          npm ci
          npm run build

      - name: Optimize Laravel for production
        run: |
          cd TeamManagerPro
          cp .env.example .env
          php artisan key:generate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

      - name: Zip artifact for deployment
        run: |
          cd TeamManagerPro
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3D4278539DB443DEA7530DC0EF9A3227 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D17950B867E44B5293E05147204AE0EE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_953427DFC7C14257B9C3AE90865EB90E }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'TeamManagerPro'
          slot-name: 'Production'
          package: .
          clean: true
          